name: Curator of the Code
on:
  workflow_run:
    workflows: ["Wulkabot Tester"]
    types:
      - completed

jobs:
  curator:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: curl https://install.python-poetry.org | python -
      - name: Update Poetry
        run: poetry self update

      - name: Install dependencies
        run: poetry install

      - name: Run pyright
        run: poetry run python -m pyright .
      - name: Run isort
        run: poetry run python -m isort .
      - name: Run black
        run: poetry run python -m black .
      - name: Push changes to GitHub
        run: git add .
        run: git commit -m "Curator workflow update"
        run: git push origin master
